### ISSUE TITLE
Undocumented dependency on pipenv

### ISSUE THREAD

**Issue by rasschaert** [iandees/aws-billing-to-slack#2]
I got this error after having run `npm install`:

```
PS C:\Users\foo\bar\aws-billing-to-slack-master> serverless deploy --slack_url="https://hooks.slack.com/services/xxxxx"

 Serverless Warning --------------------------------------

  A valid option to satisfy the declaration 'opt:credits_expire_date' could not be found.


 Serverless Warning --------------------------------------

  A valid option to satisfy the declaration 'opt:credits_remaining_date' could not be found.


 Serverless Warning --------------------------------------

  A valid option to satisfy the declaration 'opt:credits_remaining' could not be found.

Serverless: Generating requirements.txt from Pipfile...

  Error --------------------------------------------------

  Error: pipenv not found! Install it with 'pip install pipenv'.
      at ServerlessPythonRequirements.pipfileToRequirements (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\serverless-python-requirements\lib\pipenv.js:28:13)
      at ServerlessPythonRequirements.tryCatcher (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (C:\Users\foo\bar\aws-billing-to-slack-master\node_modules\bluebird\js\release\async.js:15:14)
      at runCallback (timers.js:794:20)
      at tryOnImmediate (timers.js:752:5)
      at processImmediate [as _immediateCallback] (timers.js:729:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              8.11.1
     Framework Version:         1.57.0
     Plugin Version:            3.2.2
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

It was fixed by installing pipenv via pip:
```
PS C:\Users\foo\bar\aws-billing-to-slack-master> pip install pipenv
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl (5.2MB)
     |████████████████████████████████| 5.2MB 1.6MB/s
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/c5/97/00dd42a0fc41e9016b23f07ec7f657f636cb672fad9cf72b80f8f65c6a46/virtualenv-16.7.7-py2.py3-none-any.whl (3.4MB)
     |████████████████████████████████| 3.4MB 6.4MB/s
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/ba/f8/50c2b7dbc99e05fce5e5b9d9a31f37c988c99acd4e8dedd720b7b8d4011d/virtualenv_clone-0.5.3-py2.py3-none-any.whl
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 6.4MB/s
Requirement already satisfied: pip>=9.0.1 in c:\users\foo\appdata\roaming\python\python37\site-packages (from pipenv) (19.2.1)
Requirement already satisfied: setuptools>=36.2.1 in c:\users\foo\appdata\local\programs\python\python37\lib\site-packages (from pipenv) (40.8.0)
Installing collected packages: virtualenv, virtualenv-clone, certifi, pipenv
Successfully installed certifi-2019.9.11 pipenv-2018.11.26 virtualenv-16.7.7 virtualenv-clone-0.5.3
WARNING: You are using pip version 19.2.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by iandees** [comment]
Fixed in #10
