### ISSUE TITLE
Getting Error in Deployment

### ISSUE THREAD

**Issue by VijayBattu1** [iandees/aws-billing-to-slack#36]
```
$ serverless deploy --stage="prod" --param="slack_url=https://hooks.slack.com/services/-----/-------/9k50zckCscknrYecKNksBJXu"
Running "serverless" from node_modules

Deploying app-aws-cost to stage prod (us-east-1)

**× Stack app-aws-cost-prod failed to deploy (0s)**
Environment: linux, node 12.22.9, framework 3.3.0 (local) 3.29.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: spawn pipenv ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

1 deprecation found: run 'serverless doctor' for more details
```

![image](https://github.com/VijayBattu1/Backend/blob/main/image.jpg)

**Comment by VijayBattu1** [comment]
Can Any one Help me out ???

**Comment by iandees** [comment]
This might be related to https://github.com/serverless/serverless-python-requirements/issues/694, in which case you should try `pip install -U pipenv` to get to at least pipenv v2022.5.2 and re-run the serverless command.

**Comment by iandees** [comment]
Since I haven't heard from you in a while, I'll assume this solved your problem. Feel free to leave a comment if it didn't.
